#!/usr/bin/env node
/* index.mjs — writes INDEX.md, the first file an AI reads in this repo.

   One line per file: what it is, how current it is, and enough status to
   decide whether to open it. The whole point is that answering "what did I
   think of Honey Creek?" should cost one small read and one targeted read,
   not a crawl. GENERATED — edit the files it describes, never this one.

     node tools/index.mjs           # write INDEX.md
     node tools/index.mjs --check   # exit 1 if INDEX.md is stale (CI) */

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";
import { parseTrip, splitFrontmatter } from "./lib/format.mjs";
import { parseIdea, summarize } from "./lib/wishlist.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel) => readFileSync(join(ROOT, rel), "utf8");
const ls = (rel) => (existsSync(join(ROOT, rel)) ? readdirSync(join(ROOT, rel)) : []);

export function buildIndex() {
  const out = [
    "# INDEX",
    "",
    "<!-- GENERATED by tools/index.mjs. Do not edit; edit the files listed. -->",
    "",
    "Read this first. Open only the files the question needs. Paths are relative to the repo root.",
    "",
    "## About Colin: `me/`",
    "",
  ];
  for (const f of ls("me").filter((f) => f.endsWith(".md")).sort()) {
    const { data } = splitFrontmatter(read(`me/${f}`));
    out.push(`- \`me/${f}\`: ${data.summary ?? "(no summary in frontmatter)"}`);
  }

  const kitchen = ls("kitchen").filter((f) => f.endsWith(".md")).sort();
  if (kitchen.length) {
    out.push("", "## Food and the camp kitchen: `kitchen/`", "");
    for (const f of kitchen) {
      const { data } = splitFrontmatter(read(`kitchen/${f}`));
      out.push(`- \`kitchen/${f}\`: ${data.summary ?? "(no summary in frontmatter)"}`);
    }
  }

  const trips = ls("trips").filter((s) => existsSync(join(ROOT, "trips", s, "trip.md"))).sort();
  const rows = trips.map((slug) => {
    const { registry: r, page } = parseTrip(read(`trips/${slug}/trip.md`));
    const places = existsSync(join(ROOT, "trips", slug, "places.yaml"))
      ? YAML.parse(read(`trips/${slug}/places.yaml`)).groups.flatMap((g) => g.places) : [];
    const verified = places.filter((p) => p.verified).length;
    const log = existsSync(join(ROOT, "trips", slug, "log.md")) ? read(`trips/${slug}/log.md`) : "";
    const entries = (log.match(/^## \d{4}-\d{2}-\d{2}/gm) ?? []).length;
    const retro = /^## Retro \(in progress/m.test(log) ? "in progress"
      : /^## Retro: not yet written/m.test(log) ? "pending"
      : /^## Retro/m.test(log) ? "written" : "—";
    return { slug, r, page, places: places.length, verified, entries, retro };
  });

  const byStatus = (s) => rows.filter((x) => x.r.status === s);
  const section = (title, list) => {
    if (!list.length) return;
    out.push("", `## ${title}`, "");
    for (const { slug, r, page, places, verified, entries, retro } of list) {
      const bits = [
        r.dates ?? "no dates",
        page.days ? `${page.days.length} days` : null,
        page.openQuestions?.length ? `${page.openQuestions.length} open questions` : null,
        places ? `${verified}/${places} places located` : null,
        entries ? `log ${entries} entr${entries === 1 ? "y" : "ies"}` : null,
        retro !== "—" ? `retro ${retro}` : null,
        `updated ${r.updated ?? "?"}`,
      ].filter(Boolean).join(" · ");
      out.push(`- **${r.title}** (\`trips/${slug}/\`) · ${r.status} · ${bits}`);
      if (r.why) out.push(`  ${summarize(r.why)}`);
    }
  };
  section("Planned trips", byStatus("planned"));
  section("Outlines", byStatus("outline"));
  section("Done", byStatus("done"));

  const ideas = ls("wishlist").filter((f) => f.endsWith(".md")).sort().map((f) => ({ f, ...parseIdea(read(`wishlist/${f}`)) }));
  if (ideas.length) {
    out.push("", "## Wishlist: `wishlist/`", "",
      "Ideas, not plans: one file each, with a Why, a Next and dated research notes. `months` and `mode` are what \"what fits May?\" matches against.", "");
    const MON = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    for (const { f, fm, entries } of ideas) {
      const bits = [
        fm.region, fm.mode,
        fm.months?.length ? fm.months.map((m) => MON[m]).join("/") : "no months",
        fm.days ? `${fm.days} days` : fm.nights ?? null,
        entries.length ? `${entries.length} research note${entries.length === 1 ? "" : "s"}` : null,
        `updated ${fm.updated ?? "?"}`,
      ].filter(Boolean).join(" · ");
      out.push(`- **${fm.title}** (\`wishlist/${f}\`) · ${bits}`);
      if (fm.subtitle) out.push(`  ${fm.subtitle}`);
    }
  }

  out.push(
    "",
    "## Per trip, which file answers what",
    "",
    "- `trip.md`: the plan. Frontmatter holds the registry facts (dates, status, bookings); the body has Overview, Days, Hikes, Provisions, Packing, Reservations & checks, Open questions and Notes.",
    "- `places.yaml`: every place with its coordinate, or `verified: false` and null if nobody has located it.",
    "- `log.md`: what actually happened. Planning history, on-trip notes, the retro. **Past experience lives here.**",
    "- `_gen/`: generated (sun tables, route lines). Don't read it for answers; don't edit it.",
    "",
  );
  return out.join("\n");
}

const text = buildIndex();
if (process.argv.includes("--check")) {
  const cur = existsSync(join(ROOT, "INDEX.md")) ? read("INDEX.md") : "";
  if (cur !== text) {
    console.error("INDEX.md is stale. Run: node tools/index.mjs");
    process.exit(1);
  }
  console.log("INDEX.md is current.");
} else {
  writeFileSync(join(ROOT, "INDEX.md"), text);
  console.log("wrote INDEX.md");
}
