#!/usr/bin/env node
/* macros.mjs — totals for kitchen/staples.md, computed, never hand-added.

   Reads the ```yaml foods``` block (nutrition per serving), the ```yaml meals```
   block (servings of each food) and the ```yaml days``` block (which meals make
   a day), then rewrites the table between the GENERATED markers. Targets come
   from the same file's frontmatter.

     node tools/macros.mjs          # rewrite the totals
     node tools/macros.mjs --check  # exit 1 if the totals are stale (CI) */

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";
import { splitFrontmatter } from "./lib/format.mjs";

const FILE = join(dirname(fileURLToPath(import.meta.url)), "..", "kitchen", "staples.md");
const START = "<!-- GENERATED by tools/macros.mjs — do not edit by hand -->";
const END = "<!-- /GENERATED -->";
const KEYS = ["kcal", "protein_g", "carbs_g", "fat_g"];

function block(text, tag) {
  const m = new RegExp("```yaml " + tag + "\\n([\\s\\S]*?)```").exec(text);
  if (!m) throw new Error(`no \`\`\`yaml ${tag} block in kitchen/staples.md`);
  return YAML.parse(m[1]);
}

export function compute(text) {
  const { data: fm } = splitFrontmatter(text);
  const foods = Object.fromEntries(block(text, "foods").map((f) => [f.id, f]));
  const meals = block(text, "meals");
  const days = block(text, "days");

  const sum = (parts) => {
    const t = { kcal: 0, protein_g: 0, carbs_g: 0, fat_g: 0 };
    for (const p of parts) for (const k of KEYS) t[k] += p[k];
    return t;
  };
  const mealTotals = Object.fromEntries(meals.map((m) => {
    const parts = Object.entries(m.items).map(([id, qty]) => {
      const f = foods[id];
      if (!f) throw new Error(`meal ${m.id} uses unknown food "${id}"`);
      if (KEYS.some((k) => typeof f[k] !== "number")) throw new Error(`food ${id} has no numbers yet`);
      return Object.fromEntries(KEYS.map((k) => [k, f[k] * qty]));
    });
    return [m.id, { ...m, t: sum(parts), estimated: Object.keys(m.items).some((id) => foods[id].basis !== "label") }];
  }));

  const r = (n) => Math.round(n);
  const row = (name, t) => `| ${name} | ${r(t.kcal)} | ${r(t.protein_g)} | ${r(t.carbs_g)} | ${r(t.fat_g)} |`;
  const out = [START, "", "**Per meal** (≈ means at least one ingredient is an estimate)", "",
    "| Meal | kcal | Protein g | Carbs g | Fat g |", "|---|---|---|---|---|"];
  for (const m of Object.values(mealTotals)) out.push(row(`${m.estimated ? "≈ " : ""}${m.id} · ${m.name}`, m.t));

  const tg = fm.targets;
  out.push("", `**Per day**, against the targets in \`me/food.md\` (${tg.kcal} kcal · ${tg.protein_g[0]}–${tg.protein_g[1]} g protein · ${tg.carbs_g[0]}–${tg.carbs_g[1]} g carbs · ${tg.fat_g[0]}–${tg.fat_g[1]} g fat)`, "",
    "| Day | kcal | Protein g | Carbs g | Fat g | vs target |", "|---|---|---|---|---|---|");
  for (const d of days) {
    const t = sum(d.meals.map((id) => {
      if (!mealTotals[id]) throw new Error(`day ${d.name} uses unknown meal "${id}"`);
      return mealTotals[id].t;
    }));
    const gap = [];
    const band = (v, [lo, hi], label) => { if (v < lo) gap.push(`${label} −${r(lo - v)}`); else if (v > hi) gap.push(`${label} +${r(v - hi)}`); };
    if (t.kcal < tg.kcal * 0.95) gap.push(`kcal −${r(tg.kcal - t.kcal)}`);
    band(t.protein_g, tg.protein_g, "protein");
    band(t.carbs_g, tg.carbs_g, "carbs");
    band(t.fat_g, tg.fat_g, "fat");
    out.push(`${row(d.name, t)} ${gap.length ? gap.join(", ") : "✅ on target"} |`);
  }
  out.push("", END);
  const i = text.indexOf(START), j = text.indexOf(END);
  if (i < 0 || j < 0) throw new Error("GENERATED markers missing from kitchen/staples.md");
  return text.slice(0, i) + out.join("\n") + text.slice(j + END.length);
}

const cur = readFileSync(FILE, "utf8");
const next = compute(cur);
if (process.argv.includes("--check")) {
  if (cur !== next) { console.error("kitchen/staples.md totals are stale. Run: node tools/macros.mjs"); process.exit(1); }
  console.log("kitchen/staples.md totals are current.");
} else {
  writeFileSync(FILE, next);
  console.log("wrote kitchen/staples.md totals");
}
