#!/usr/bin/env node
/* now.mjs — the briefing: what's going on today, computed from the files.

     node tools/now.mjs              # today
     node tools/now.mjs 2026-10-14   # as if it were that date

   The session-start hook prints this so every new session opens knowing the
   next trip, what's open on it, and what's due. Nothing here is stored: it
   is derived from trips/, wishlist/ and me/ each time, so it cannot go
   stale the way a hand-kept status list does. Booking-window dates are
   computed from each trip's `booking:` targets and me/booking.md's
   leadMonths, never typed. */

import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";
import { parseTrip } from "./lib/format.mjs";
import { monthsBefore } from "./lib/dates.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel) => readFileSync(join(ROOT, rel), "utf8");
const has = (rel) => existsSync(join(ROOT, rel));
const ls = (rel) => (has(rel) ? readdirSync(join(ROOT, rel)) : []);

const localIso = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
const TODAY = process.argv[2] ?? localIso(new Date());
const day = (iso) => Date.UTC(+iso.slice(0, 4), +iso.slice(5, 7) - 1, +iso.slice(8, 10));
const diff = (a, b) => Math.round((day(b) - day(a)) / 864e5); // days from a to b
const addDays = (iso, n) => new Date(day(iso) + n * 864e5).toISOString().slice(0, 10);
const DOW = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const MON = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const fmt = (iso) => { const d = new Date(day(iso)); return `${DOW[d.getUTCDay()]} ${MON[d.getUTCMonth()]} ${d.getUTCDate()}`; };
const plain = (s) => String(s ?? "").replace(/\*\*|\*|`/g, "").replace(/<br>/g, " ").replace(/\s+/g, " ").trim();
const clip = (s, n = 110) => (s.length > n ? s.slice(0, s.lastIndexOf(" ", n)) + "…" : s);

/* ------------------------------------------------------------ gather */

const trips = ls("trips").filter((s) => has(`trips/${s}/trip.md`)).map((slug) => {
  const { registry: r, page } = parseTrip(read(`trips/${slug}/trip.md`));
  const start = r.start ?? r.target ?? null;
  const end = start && r.days ? addDays(start, r.days - 1) : start;
  const log = has(`trips/${slug}/log.md`) ? read(`trips/${slug}/log.md`) : "";
  const entries = [...log.matchAll(/^## (\d{4}-\d{2}-\d{2}) · (.+)$/gm)].map((m) => ({ date: m[1], title: m[2] }));
  return { slug, r, page, start, end, dated: !!r.start, entries, retro: /^## Retro/m.test(log) };
});

const leads = {};
for (const m of read("me/booking.md").matchAll(/```yaml\n([\s\S]*?)```/g)) {
  for (const row of YAML.parse(m[1]) ?? []) leads[row.system] = row.leadMonths ?? null;
}

const gear = [];
for (const m of (has("me/gear.md") ? read("me/gear.md") : "").matchAll(/```yaml\n([\s\S]*?)```/g)) {
  for (const it of YAML.parse(m[1]) ?? []) if (["need", "replace", "unknown"].includes(it?.state)) gear.push(`${plain(it.name)} (${it.state})`);
}

/* ------------------------------------------------------------ print */

const out = [];
const say = (...lines) => out.push(...(lines.length ? lines : [""]));
say(`# Briefing · ${fmt(TODAY)}, ${TODAY}`);
say(`Generated by tools/now.mjs from the files. Everything below is derived; open the cited file before acting on a line.`);

const live = (t) => !["done", "shelved"].includes(t.r.status);
const active = trips.filter((t) => t.dated && t.start <= TODAY && TODAY <= t.end && live(t));
const upcoming = trips.filter((t) => t.start && t.start > TODAY && live(t)).sort((a, b) => (a.start < b.start ? -1 : 1));
const next = active[0] ?? upcoming[0];

if (active.length) {
  for (const t of active) {
    const n = diff(t.start, TODAY) + 1;
    const d = t.page.days?.find((x) => x.date === TODAY);
    say("", `## On the road: ${t.r.title}, day ${n} of ${t.r.days}`);
    if (d) say(`Today: ${plain(d.title)}. Tonight: ${plain(d.overnight?.name) || "not recorded"}. (trips/${t.slug}/trip.md)`);
    say(`Anything that happens → /log.`);
  }
}

if (next && !active.includes(next)) {
  const t = next, days = diff(TODAY, t.start);
  say("", `## Next trip: ${t.r.title} (trips/${t.slug}/)`);
  say(`${t.dated ? "Leaves" : "Target"} ${fmt(t.start)} · ${days} days out · status ${t.r.status}${t.dated ? "" : " (dates are a target, not booked)"}`);
  if (t.r.next) say(`Next step (trip.md): ${clip(plain(t.r.next), 200)}`);
  const pre = [14, 7, 1].map((k) => ({ k, date: addDays(t.start, -k) })).filter((p) => p.date >= TODAY);
  if (days <= 30 && pre.length) say(`/preflight: ${pre.map((p) => `T-${p.k} ${p.date === TODAY ? "**today**" : fmt(p.date)}`).join(" · ")}`);
  const qs = t.page.openQuestions ?? [];
  if (qs.length) {
    say(`Open questions (${qs.length}):`);
    for (const q of qs.slice(0, 8)) say(`- ${clip(plain(q.question))}`);
    if (qs.length > 8) say(`- …and ${qs.length - 8} more in trip.md`);
  }
  const unchecked = (t.page.reservations ?? []).filter((x) => !x.booked);
  if (unchecked.length) say(`Unchecked items in Reservations & checks: ${unchecked.length} (trip.md)`);
  const recent = t.entries.slice(-3).reverse();
  if (recent.length) {
    say(`Latest log entries (trips/${t.slug}/log.md; decisions there can be newer than trip.md):`);
    for (const e of recent) say(`- ${e.date} · ${clip(plain(e.title))}`);
  }
}

// Booking windows: computed, soonest first. Only unbooked rows.
const windows = [];
for (const t of trips.filter(live)) for (const b of t.r.booking ?? []) {
  if (b.booked || b.done || !b.target) continue;
  const lead = leads[b.system];
  windows.push({ t, b, opens: lead == null ? null : monthsBefore(b.target, lead) });
}
const soon = windows.filter((w) => w.opens && diff(TODAY, w.opens) <= 120).sort((a, b) => (a.opens < b.opens ? -1 : 1));
const unknown = windows.filter((w) => !w.opens);
if (soon.length || unknown.length) {
  say("", `## Booking windows not marked booked (computed: target minus leadMonths, me/booking.md)`);
  for (const w of soon) {
    const d = diff(TODAY, w.opens);
    const when = d < 0 ? "open now" : d === 0 ? "opens TODAY" : `opens ${fmt(w.opens)}, in ${d} days`;
    say(`- ${when} · ${plain(w.b.what)} · ${w.b.system} · ${w.t.slug}`);
  }
  const later = windows.filter((w) => w.opens && diff(TODAY, w.opens) > 120).length;
  if (later) say(`- ${later} more open later than 120 days from now.`);
  if (unknown.length) say(`- ${unknown.length} with no computable window (state park, private, etc.): confirm by hand. Trips: ${[...new Set(unknown.map((w) => w.t.slug))].join(", ")}`);
}

const needsRetro = trips.filter((t) => t.end && t.end < TODAY && !t.retro && t.r.status !== "outline");
if (needsRetro.length) say("", `## Retro pending`, ...needsRetro.map((t) => `- ${t.r.title}: trip ended ${fmt(t.end)} → /retro ${t.slug}`));
const stale = trips.filter((t) => t.dated && t.end < TODAY && t.r.status !== "done");
if (stale.length) say("", `## Stale status`, ...stale.map((t) => `- ${t.slug} ended ${fmt(t.end)} but is still \`${t.r.status}\` → set status: done`));

if (gear.length) say("", `## Gear not settled (me/gear.md)`, `- ${gear.join(" · ")}`);

const later = upcoming.filter((t) => t !== next);
if (later.length) say("", `## After that`, ...later.map((t) => `- ${fmt(t.start)} · ${t.r.title} (${t.r.status}${t.dated ? "" : ", target"})`));
const undated = trips.filter((t) => !t.start && !["done", "shelved"].includes(t.r.status));
if (undated.length) say(...undated.map((t) => `- no date · ${t.r.title} (${t.r.status})`));
const shelved = trips.filter((t) => t.r.status === "shelved");
if (shelved.length) say(`- shelved, not live: ${shelved.map((t) => t.r.title).join(", ")}`);

const ideas = ls("wishlist").filter((f) => f.endsWith(".md"));
if (ideas.length) say("", `## Ideas`, `${ideas.length} in wishlist/ (see INDEX.md). Explore one with /daydream.`);

console.log(out.join("\n"));
